# -*- coding: utf-8 -*-
"""Task 6 Decision Tree Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XMHw2uUKMBp94AlHw_VkCIbd3VLYJrxP

# **TASK 6 : Building a Decision Tree Classifier**

### Author:Harshdeep Singh Narula

Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Importing Datasets"""

data=pd.read_csv("Iris.csv")
data

data.columns

df=data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
df

Y=data["Species"]
Y

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
y

type(y)

type(df)

"""Model Fitting"""

from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(df,y)

!pip install pydotplus
!pip install graphviz
!pip install six

"""Visualising the Decision Tree"""

from six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

dot_data = StringIO()
export_graphviz(dtc, out_file=dot_data,
                feature_names=['SepalLengthCm','SepalWidthCm',
                               'PetalLengthCm','PetalWidthCm'],  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

